### ISSUE TITLE
Username, Password, or Address is wrong.

### ISSUE THREAD

**Issue by systxix** [rroller/dahua#145]
## Configuration

```yaml

Add your logs here.

```

## Describe the bug
While adding camera to HA i'm getting this error: "Username, Password, or Address is wrong."
Using default username admin/admin

Are these cameras supported?

IPC-HFW1320S
IPC-HFW1300S
IPC-HFW2320R-ZS

## Debug log

```text

Add your logs here.

```

**Comment by AndreTzerra** [comment]
I have the same problem.

When I try to add my XVR5108HS I have the same problem.
In the past I have managed to get a connection once. 
Last week I had to change my complete network IP range.
(Migrated from 192.168.1.X to 10.11.1.X)

 And now I can't get it to work again.
I'm sure that I use the right Name, password IP and port settings.
Below is the output from the Dahua log:

  _File "/config/custom_components/dahua/client.py", line 657, in get
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://10.11.1.180:443/cgi-bin/magicBox.cgi?action=getMachineName')_

When I go to https://10.11.1.180:443/cgi-bin/magicBox.cgi?action=getMachineName, I get "name=XVR".

**Comment by intelwolf** [comment]
For me it worked after changing the source code from client.py to below (in the custom_components folder). As it appeared my cam only provided that information after authentication and this fixed it:

_#        self._base = "{0}://{1}:{2}".format(protocol, address, port)
         self._base = "{0}://{1}:{2}@{3}:{4}".format(protocol, username, password, address, port)_

**Comment by rroller** [comment]
Thanks, this helps a lot. Can you try this (make sure to revert the code change)...
When adding the cam, for the address do this... but your username and password...
user:password@IP_ADDRESS
for example...

admin:pass@192.168.1.203

**Comment by AndreTzerra** [comment]
The option : __self.base = "{0}://{1}:{2}@{3}:{4}".format(protocol, username, password, address, port)_ did not work for me.

For me the solution looks very simple:
I used port 80 all the time. Let's give 443 one try. Thats it! 

After deleting and reinstalling the component it works. 👍

**Comment by intelwolf** [comment]
> 

That was my initial attempt (adding username:passwd to the address field). The result was that my camera got initialised without errors and all but I couldn't get the streams working. Makes sense I guess since the rtsp streams already have username password in it and using this method it would duplicate that.

**Comment by systxix** [comment]
> Thanks, this helps a lot. Can you try this (make sure to revert the code change)... When adding the cam, for the address do this... but your username and password... user:password@IP_ADDRESS for example...
> 
> admin:pass@192.168.1.203

I can add camera like this but like intelwolf mentioned stream is not working.

**Comment by si458** [comment]
have you tried:
1. delete device/integration
2. updating to the latest version 0.9.39
3. enable debug in configuration.yaml
4. reboot HA
5. try adding the device again and then checking logs
(also check the user/pass works in your browser works directy from the camera ip first)

**Comment by systxix** [comment]
This error originated from a custom integration.

Logger: custom_components.dahua
Source: custom_components/dahua/client.py:670
Integration: Dahua (documentation, issues)
First occurred: 14:40:44 (1 occurrences)
Last logged: 14:40:44

Could not connect to Dahua device. For iMou devices see https://github.com/rroller/dahua/issues/6
Traceback (most recent call last):
  File "/config/custom_components/dahua/config_flow.py", line 177, in _test_credentials
    data = await client.get_machine_name()
  File "/config/custom_components/dahua/client.py", line 101, in get_machine_name
    return await self.get("/cgi-bin/magicBox.cgi?action=getMachineName")
  File "/config/custom_components/dahua/client.py", line 687, in get
    raise exception
  File "/config/custom_components/dahua/client.py", line 670, in get
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url=URL('http://192.168.88.246:80/cgi-bin/magicBox.cgi?action=getMachineName')

**Comment by si458** [comment]
> 401, message='Unauthorized',

you need to verify the user/pass is correct bu going to the URL it shows directly in your browser,
if the user/pass is correct you should get like a 404 error or 200 or something else, but not a 401 error

**Comment by systxix** [comment]
User and pass is correct. When opening http://192.168.88.246/cgi-bin/magicBox.cgi?action=getMachineName it asks for user/pass and then displays camera name=2A01ED7PAA00426

**Comment by nbmi** [comment]
I have a Dahua N43AM5Z. Does anyone know if this is significantly different from supported cams?

I cannot get past the integration login using any suggestions in this thread. When I visit the site in browser (http://192.168.1.10/cgi-bin/magicBox.cgi?action=getMachineName) I get a 404. In the HA logs after trying to add the integration, I also see a 404. Even when using un:pw@192.168.1.10 for the host address.

Over https using the same URL as above, I can't connect at all.

I have verified un/pw is correct by logging in at http://192.168.1.10/.

**Comment by giedriuskilcauskas-cujo** [comment]
After camera reset I was unable to setup camera in Integration, but while checking suggestion by @nbmi (which was Enabled, btw), I've noticed setting `Private Protocol Authentication Mode` (in the same location). Once I've changed to `Compatibility Mode`, it started working.

**Comment by alnsiuenrasd** [comment]
After exploring all of the suggestions provided here, I finally just reflashed home assistant and started all over. Once the Dahua integration was installed through HACS I was able to add all of my cameras with no issues. Perhaps this is an issue with Home Assistant?

**Comment by gnkarn** [comment]
i have tried everything mentioned  above , but still  the same error , indicating error with name password or address , 
the url test works ok   from  browser . something else i could try ?, tks

**Comment by gnkarn** [comment]
problem solved , it was port number 443 instead of 80

**Comment by NicusorFlorinBaluta** [comment]
hello, i have the same issue, but i can't find this CGI setting @nbmi  is talking about
i tried the other solutions and they didn't work
my camera model is IPC-F42FE
Can someone help me please?
I managed to compose a working rtsp url, which i used in vlc without issue, so the ip/username/password are fine

**Comment by si458** [comment]
> hello, i have the same issue, but i can't find this CGI setting @nbmi  is talking about
> i tried the other solutions and they didn't work
> my camera model is IPC-F42FE
> Can someone help me please?
> I managed to compose a working rtsp url, which i used in vlc without issue, so the ip/username/password are fine

Are u using special characters in tbe password?
I found with one unit we have, it was fiddly with special characters so we changed it to a long number n letters one and it just worked then?

**Comment by NicusorFlorinBaluta** [comment]
no special characters, it's the default password. i also just noticed i cannot access the camera by entering the ip address into the browser

**Comment by si458** [comment]
Have u tried https://THEIP ?

**Comment by NicusorFlorinBaluta** [comment]
Did now, still no spark :(

**Comment by zios0007** [comment]
Several unrelated causes have collected in this thread over four years. Two are worth separating.

**If the camera's web UI works but the integration says the password is wrong**, check whether the camera answers with Basic rather than Digest. That case is fixed: the integration now answers a Basic challenge instead of reading it as a wrong password (#733, in 0.10.x). Anyone still hitting this on a current version has a different problem and should say so with a debug log.

**@NicusorFlorinBaluta your case is not that one.** You said the camera does not open in a browser by IP either. If the web UI will not load, nothing here can log in, and what needs fixing is the camera's network settings or the account, not the integration.

@rroller closing this and asking anyone still affected on a current version to open a fresh issue with a version and a debug log would lose nothing. The thread has no single cause left in it.
