### ISSUE TITLE
Multiple server disconnected on Dahua XVR5x08-S2

### ISSUE THREAD

**Issue by hllhll** [rroller/dahua#146]
## Version of the custom_component
HACS 0.9.34
Actual DVR Device is Series 4 "lite" Dahua XVR5108HS-S2

## Describe the bug
This is roughly working, but lovelace card occasional show error (X) in the image. It re-loads a couple of seconds later,
Live preview after clicking the camera seem to be working better, but sometime gets stuck/buffering a bit as well and resumes playback (I Don't know how well this feature should work, maybe this is how this works in HA).
To compare, loading VLC on rtsp://xxxxx:xxxx@xxxxxxx:554/cam/realmonitor?channel=2&subtype=0 works flawlessly

## Debug log
```text
home-assistant   | 2022-01-20 22:01:08 ERROR (MainThread) [aiohttp.server] Error handling request
home-assistant   | Traceback (most recent call last):
home-assistant   |   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
home-assistant   |     resp = await self._request_handler(request)
home-assistant   |   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
home-assistant   |     resp = await handler(request)
home-assistant   |   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
home-assistant   |     return await handler(request)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
home-assistant   |     return await handler(request)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
home-assistant   |     return await handler(request)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
home-assistant   |     return await handler(request)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
home-assistant   |     return await handler(request)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
home-assistant   |     return await handler(request)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
home-assistant   |     result = await result
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 618, in get
home-assistant   |     return await self.handle(request, camera)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 636, in handle
home-assistant   |     image = await _async_get_image(
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 166, in _async_get_image
home-assistant   |     image_bytes = await camera.async_camera_image(
home-assistant   |   File "/config/custom_components/dahua/camera.py", line 226, in async_camera_image
home-assistant   |     return await self._coordinator.client.async_get_snapshot(self._channel_number)
home-assistant   |   File "/config/custom_components/dahua/client.py", line 66, in async_get_snapshot
home-assistant   |     return await self.get_bytes(url)
home-assistant   |   File "/config/custom_components/dahua/client.py", line 640, in get_bytes
home-assistant   |     response = await auth.request("GET", self._base + url)
home-assistant   |   File "/config/custom_components/dahua/digest.py", line 50, in request
home-assistant   |     return await self._handle_401(response)
home-assistant   |   File "/config/custom_components/dahua/digest.py", line 151, in _handle_401
home-assistant   |     return await self.request(
home-assistant   |   File "/config/custom_components/dahua/digest.py", line 46, in request
home-assistant   |     response = await self.session.request(method, url, headers=headers, **kwargs)
home-assistant   |   File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
home-assistant   |     await resp.start(conn)
home-assistant   |   File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 890, in start
home-assistant   |     message, payload = await self._protocol.read()  # type: ignore
home-assistant   |   File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 604, in read
home-assistant   |     await self._waiter
home-assistant   | aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

**Comment by hllhll** [comment]
Seems like it stopped completely after a bit... 
So I can confirm this is working the above DVR :) awesome, thanks

**Comment by hllhll** [comment]
That's still happens from time to time
