### ISSUE TITLE
Error calling service dahua/vto_open_door: Bad request 400

### ISSUE THREAD

**Issue by alve89** [rroller/dahua#154]
## Version of the custom_component

0.5.0 from latest release

## Configuration
I'm using an VTO2202F-P-S2, that's my configuration:
![image](https://user-images.githubusercontent.com/11487054/151697974-04b14f5a-38f4-434a-b817-3197b7136bb2.png)

HA integration is added through GUI.

configuration.yaml:
```
button:
  - platform: mqtt
    unique_id: dahua_vto_open_door_btn
    name: "Haustür öffnen"
    command_topic: "DahuaVTO/ha/door/open"
    payload_press: "1"
    qos: 0
    retain: false
```

## Describe the bug
It's about the button to open the door (`dahua_vto_open_door_btn` aka `Haustür öffnen`). Clicking this button sometimes (and sometimes not, I can't see any pattern) throws this error. The service is still called and the door is opened, but HA throws this error. Sometimes there's a voice feedback from the VTO, sometimes not. Sometimes the voice feedback is repeated multiple times (by now three times maximum). It's a very weird behavior.

I'd really like to give you a more precise description but I really can't see any pattern for this behavior.
I already reduced the "recognition time" in the VTO configuration (from default 15 seconds to 1 second) but still no change.

## Debug log

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/dahua/client.py:657 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 12:20:12 (1 occurrences) 
Last logged: 12:20:12

[2971219472] 400, message='Bad Request', url=URL('http://192.168.1.108:80/cgi-bin/accessControl.cgi?action=openDoor&UserID=101&Type=Remote&channel=1')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/config/custom_components/dahua/camera.py", line 325, in async_vto_open_door
    await self._coordinator.client.async_access_control_open_door(door_id)
  File "/config/custom_components/dahua/client.py", line 525, in async_access_control_open_door
    return await self.get(url)
  File "/config/custom_components/dahua/client.py", line 671, in get
    raise exception
  File "/config/custom_components/dahua/client.py", line 657, in get
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('http://192.168.1.108:80/cgi-bin/accessControl.cgi?action=openDoor&UserID=101&Type=Remote&channel=1')
```

**Comment by mattclar** [comment]
I have this also

**Comment by Giotrumpet** [comment]
Same here with a VTO2101E-P-S1

**Comment by cabral92** [comment]
Same issue, any news ?

**Comment by alve89** [comment]
Hi @rroller, did you solve this problem?

**Comment by Suxsem** [comment]
Hi think I found the issue. The GET request should not contain the UserId parameter.
@rroller Any chance you can change it in client.py?
Do you prefer a PR?

**Comment by kiklhorn** [comment]
+1

**Comment by dudetryhard** [comment]
+1
Same with VTO2202

**Comment by Dieghito72** [comment]
Hi, can confirm same issue on a DHI-VTO2201F-P Firmware: 4.500.0000001.0.R,build:2021-07-13.

@rroller thank you very much for the great work, form me the integration works great apart this, since this issue has been opened long time ago, is there any chance that will be fixed?

As soon as possible I will try the suggested solution provide by @Suxsem and let you know

**Comment by Dieghito72** [comment]
After some experiment, unfortunately the work around suggested by @Suxsem didn't work, anyway I have additional info.

The VTO manage two contacts , one for cars and one for pedestrians.

When I call the service with DoorID = 1, the first gate opens, but 404 is raised.
When I call the service with DoorID = 2, the second gate opens and no error is raised.

**Comment by LubikR** [comment]
+1

**Comment by infrat** [comment]
+1 any updates regarding this issue?

**Comment by jcortizronda** [comment]
I have the same issue, any news about this?

**Comment by Galfik-PL** [comment]
Confirm. After last component modifications I can't open doorbell using action "Dahua: Open via VTO". After using this action i have error: 
niepowodzenie wykonania akcji dahua/vto_open_door. 400, message='Bad Request', url='http://192.168.88.10/cgi-bin/accessControl.cgi?action=openDoor&UserID=101&Type=Remote&channel=1'

I changing enable CGI on/off, disabling https - without effect, Even I change userID to 1 on client .py Someone can help?

**Comment by Nicols07** [comment]
Hi, i have the same problem. 
And my automation failed in the middle with this error ….
If someone have an idea…..

**Comment by Nicols07** [comment]
Are there any people here looking for a solution to this problem?

**Comment by zios0007** [comment]
@Nicols07 yes — and sorry it took someone this long to say so. @alve89's original report is better than it looks, and one detail in it may be the whole answer.

> Sometimes the voice feedback is repeated multiple times (by now three times maximum).

**Three.** The digest authentication layer sends a request up to exactly three times:

```python
MAX_AUTH_ATTEMPTS = 3
...
for _ in range(MAX_AUTH_ATTEMPTS):
    ...
    response = await self.session.request(method, url, headers=attempt_headers, **kwargs)
    if response.status != 401:
        return response
    challenge = self._parse_401(response)
```

That is ordinary HTTP digest behaviour — send, get a `401` with a challenge, send again with credentials. It is correct for a *read*. `accessControl.cgi?action=openDoor` is not a read: it is a command with a physical effect, and each attempt is a separate HTTP request the device receives.

So a plausible account of both your symptoms, matching the numbers: the VTO acts on an attempt, answers `401` anyway, the client retries with the challenge, the VTO acts again — up to three times — and one of those exchanges ends in the `400` you see. The door opens, the voice plays more than once, and Home Assistant reports an error. That is exactly the combination @alve89 described and could not find a pattern in.

**I want to be clear this is a hypothesis, not a diagnosis.** It fits the count and both symptoms, but it requires the camera to act on a request it then rejects, and I have no VTO that does this to confirm it. Nobody has captured the exchange.

**Nothing else in the integration can do this.** `button.py` and `camera.py` each call the client once, and `_request` calls the auth layer once — so the digest retry loop is the only path in this code that can deliver one `openDoor` more than once. That is what makes the count worth taking seriously rather than treating it as coincidence.

**One wrinkle I should own, because it is the obvious objection.** On the first attempt with no cached challenge, **no `Authorization` header is sent at all**. A device that acted on a wholly unauthenticated request would have a security problem; more likely it rejects that one, and only attempts two and three carry credentials — which predicts **two** actions, not three. So "three" matches the request count exactly, and matches the *voice* count only if the VTO acts on an unauthenticated request. That is the part a capture would settle.

**Why this may already be fixed.** @alve89 was on **0.5.0**, from January 2022. Since then the digest challenge is cached and shared per device rather than rediscovered per request, so the first attempt usually carries valid credentials and never sees a `401` at all — which would make the retry loop, and this whole failure, much rarer.

**That landed in 0.9.88, on 5 September 2026 — five months after you posted.** So you were almost certainly running a version without it, and your report is not evidence the fix failed; it is evidence nobody has checked since. Which makes the question a simple one.

**Has this happened since you updated?** If you are still on something from April, updating is itself the test. If you are on 0.10.x and it still happens —

- does the door open, every time it errors?
- how many times does the voice play on a failure?
- does it correlate with the doorbell having been idle for a while (a stale challenge) rather than with repeated presses?

That last one is the most diagnostic. If it only happens on the first press after a long idle period, the digest-retry account is almost certainly right and the fix belongs in the auth layer, not in the door code.

**One thing this has already changed.** There is an open PR (#722) adding a fallback so that VTOs with no `accessControl` CGI endpoint at all can open a door another way. Because of this issue, it deliberately **refuses to fall back on a `400`** — retrying a command on a second transport when the door may already have opened is precisely the wrong thing to do, and your report is the reason that rule is written down. So this thread has been useful even while unanswered.

If you can answer any of the above, please do. If the VTO has since been replaced or the problem has gone, that is worth saying too — it would tell us the digest change fixed it.
