### ISSUE TITLE
VTO2000A keeps trying to getConfig Lighting?

### ISSUE THREAD

**Issue by si458** [rroller/dahua#156]
## Version of the custom_component
0.9.36

## Configuration
disabled all events, then also after initialised has failed, i clicked configure, and disabled all options except the 'camera enabled'

## Describe the bug
i cant seem to initialise the integration, it adds the device perfectly fine, but never starts?

## Debug log
```
2022-02-06 19:22:00 INFO (Thread-116) [custom_components.dahua] Starting DahuaVtoEventThread
2022-02-06 19:22:00 DEBUG (Thread-116) [custom_components.dahua] Connecting to VTO event stream
2022-02-06 19:22:00 DEBUG (Thread-116) [custom_components.dahua] VTO connection established
2022-02-06 19:22:00 DEBUG (Thread-116) [custom_components.dahua] Prepare pre-login message
2022-02-06 19:22:01 DEBUG (Thread-116) [custom_components.dahua] Prepare login message
2022-02-06 19:22:01 INFO (Thread-116) [custom_components.dahua] Get access control configuration
2022-02-06 19:22:01 INFO (Thread-116) [custom_components.dahua] Get version
2022-02-06 19:22:01 INFO (Thread-116) [custom_components.dahua] Get serial number
2022-02-06 19:22:01 INFO (Thread-116) [custom_components.dahua] Get device type
2022-02-06 19:22:01 INFO (Thread-116) [custom_components.dahua] Attach event manager
2022-02-06 19:22:01 INFO (Thread-116) [custom_components.dahua] Device Type: VTO2000A
2022-02-06 19:22:01 INFO (Thread-116) [custom_components.dahua] Version: 3.120.000000001.0.R, Build Date: 2019-02-22
2022-02-06 19:22:01 INFO (Thread-116) [custom_components.dahua] Hold time: 5
2022-02-06 19:22:01 INFO (Thread-116) [custom_components.dahua] Serial Number: 5D09714PAZBXXXX
2022-02-06 19:22:01 WARNING (MainThread) [custom_components.dahua] Failed to sync device state
Traceback (most recent call last):
  File "/config/custom_components/dahua/__init__.py", line 279, in _async_update_data
    results = await asyncio.gather(*coros)
  File "/config/custom_components/dahua/client.py", line 193, in async_get_config_lighting
    raise e
  File "/config/custom_components/dahua/client.py", line 187, in async_get_config_lighting
    return await self.async_get_config("Lighting[{0}][{1}]".format(channel, profile_mode))
  File "/config/custom_components/dahua/client.py", line 172, in async_get_config
    return await self.get(url)
  File "/config/custom_components/dahua/client.py", line 675, in get
    raise exception
  File "/config/custom_components/dahua/client.py", line 661, in get
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('http://192.168.1.100/cgi-bin/configManager.cgi?action=getConfig&name=Lighting%5B1%5D%5B0%5D')
2022-02-06 19:22:01 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 8.873 seconds (success: False)
2022-02-06 19:22:02 DEBUG (Thread-116) [custom_components.dahua] VTO Data received: {'Action': 'Start', 'Code': 'CallNoAnswered', 'Data': {'CallID': '91', 'LocaleTime': '2022-02-06 19:22:01', 'UTC': 1644175321.0}, 'Index': 9900, 'Param': {'CallID': '91'}, 'deviceType': 'VTO2000A', 'serialNumber': '5D09714PAZBXXXX', 'DeviceName': 'VTO2000A'}
2022-02-06 19:22:02 DEBUG (Thread-116) [custom_components.dahua] VTO Data received: {'Action': 'Start', 'Code': 'RtspSessionDisconnect', 'Data': {'Device': '::ffff:192.168.168.170', 'LocaleTime': '2022-02-06 19:22:01', 'StreamType': 'Extra1', 'UTC': 1644175321.0, 'UserAgent': ' LibVLC\\/3.0.16 (LIVE555 Streaming Media v2016.11.28)'}, 'Index': 0, 'Param': None, 'deviceType': 'VTO2000A', 'serialNumber': '5D09714PAZBXXXX', 'DeviceName': 'VTO2000A'}
2022-02-06 19:22:07 DEBUG (Thread-113) [custom_components.dahua] Keep alive
```

**Comment by rroller** [comment]
Are you able to load either of these URLs in your browser?

* http://192.168.1.100/cgi-bin/configManager.cgi?action=getConfig&name=Lighting[0][0]
* http://192.168.1.100/cgi-bin/configManager.cgi?action=getConfig&name=Lighting[1][0]

From the log, it looks like it is trying to use channel 1. I suspect channel 0 will work. Are you using an NVR or adding the camera directly?

**Comment by rroller** [comment]
Try removing the integration and on the configuration screen select channel 0

**Comment by si458** [comment]
@rroller running both those URLs in my browser just returns errors
```
Error
Unknown error! error code was not set in service!
```

also i have already tried setting it to channel 0 but same error

my device is a Dahua VTO2000A (its the intercom module WITHOUT the sip, so first generation)

**Comment by si458** [comment]
```
2022-02-13 20:25:46 INFO (MainThread) [homeassistant.setup] Setup of domain dahua took 0.0 seconds
2022-02-13 20:25:54 INFO (Thread-2276) [custom_components.dahua] Starting DahuaVtoEventThread
2022-02-13 20:25:54 INFO (Thread-2276) [custom_components.dahua] Get access control configuration
2022-02-13 20:25:54 INFO (Thread-2276) [custom_components.dahua] Get version
2022-02-13 20:25:54 INFO (Thread-2276) [custom_components.dahua] Get serial number
2022-02-13 20:25:54 INFO (Thread-2276) [custom_components.dahua] Get device type
2022-02-13 20:25:54 INFO (Thread-2276) [custom_components.dahua] Attach event manager
2022-02-13 20:25:55 WARNING (MainThread) [custom_components.dahua] Failed to sync device state
Traceback (most recent call last):
  File "/config/custom_components/dahua/__init__.py", line 279, in _async_update_data
    results = await asyncio.gather(*coros)
  File "/config/custom_components/dahua/client.py", line 193, in async_get_config_lighting
    raise e
  File "/config/custom_components/dahua/client.py", line 187, in async_get_config_lighting
    return await self.async_get_config("Lighting[{0}][{1}]".format(channel, profile_mode))
  File "/config/custom_components/dahua/client.py", line 172, in async_get_config
    return await self.get(url)
  File "/config/custom_components/dahua/client.py", line 675, in get
    raise exception
  File "/config/custom_components/dahua/client.py", line 661, in get
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('http://192.168.1.100:80/cgi-bin/configManager.cgi?action=getConfig&name=Lighting%5B0%5D%5B0%5D')
2022-02-13 20:25:55 WARNING (MainThread) [homeassistant.config_entries] Config entry '5D09714PAZB4984' for dahua integration not ready yet; Retrying in background
2022-02-13 20:25:55 INFO (Thread-2276) [custom_components.dahua] Hold time: 5
2022-02-13 20:25:55 INFO (Thread-2276) [custom_components.dahua] Version: 3.120.000000001.0.R, Build Date: 2019-02-22
2022-02-13 20:25:55 INFO (Thread-2276) [custom_components.dahua] Serial Number: 5D09714PAZB4984
2022-02-13 20:25:55 INFO (Thread-2276) [custom_components.dahua] Device Type: VTO2000A
2022-02-13 20:26:07 INFO (Thread-2279) [custom_components.dahua] Starting DahuaVtoEventThread
2022-02-13 20:26:08 INFO (Thread-2279) [custom_components.dahua] Get access control configuration
2022-02-13 20:26:08 INFO (Thread-2279) [custom_components.dahua] Get version
2022-02-13 20:26:08 INFO (Thread-2279) [custom_components.dahua] Get serial number
2022-02-13 20:26:08 INFO (Thread-2279) [custom_components.dahua] Get device type
2022-02-13 20:26:08 INFO (Thread-2279) [custom_components.dahua] Attach event manager
2022-02-13 20:26:08 INFO (Thread-2279) [custom_components.dahua] Hold time: 5
2022-02-13 20:26:08 INFO (Thread-2279) [custom_components.dahua] Device Type: VTO2000A
2022-02-13 20:26:08 INFO (Thread-2279) [custom_components.dahua] Version: 3.120.000000001.0.R, Build Date: 2019-02-22
2022-02-13 20:26:08 INFO (Thread-2279) [custom_components.dahua] Serial Number: 5D09714PAZB4984
2022-02-13 20:26:08 WARNING (MainThread) [custom_components.dahua] Failed to sync device state
Traceback (most recent call last):
  File "/config/custom_components/dahua/__init__.py", line 279, in _async_update_data
    results = await asyncio.gather(*coros)
  File "/config/custom_components/dahua/client.py", line 193, in async_get_config_lighting
    raise e
  File "/config/custom_components/dahua/client.py", line 187, in async_get_config_lighting
    return await self.async_get_config("Lighting[{0}][{1}]".format(channel, profile_mode))
  File "/config/custom_components/dahua/client.py", line 172, in async_get_config
    return await self.get(url)
  File "/config/custom_components/dahua/client.py", line 675, in get
    raise exception
  File "/config/custom_components/dahua/client.py", line 661, in get
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('http://192.168.1.100:80/cgi-bin/configManager.cgi?action=getConfig&name=Lighting%5B0%5D%5B0%5D')
```

**Comment by si458** [comment]
> Got it. Let me see if I can add a fix for this.

@rroller debug logs for you, sorry i forgot to enable it!
```
2022-02-13 20:32:51 INFO (Thread-116) [custom_components.dahua] Starting DahuaVtoEventThread
2022-02-13 20:32:51 DEBUG (Thread-116) [custom_components.dahua] Connecting to VTO event stream
2022-02-13 20:32:51 DEBUG (Thread-116) [custom_components.dahua] VTO connection established
2022-02-13 20:32:51 DEBUG (Thread-116) [custom_components.dahua] Prepare pre-login message
2022-02-13 20:32:51 DEBUG (Thread-116) [custom_components.dahua] Prepare login message
2022-02-13 20:32:52 INFO (Thread-116) [custom_components.dahua] Get access control configuration
2022-02-13 20:32:52 INFO (Thread-116) [custom_components.dahua] Get version
2022-02-13 20:32:52 INFO (Thread-116) [custom_components.dahua] Get serial number
2022-02-13 20:32:52 INFO (Thread-116) [custom_components.dahua] Get device type
2022-02-13 20:32:52 INFO (Thread-116) [custom_components.dahua] Attach event manager
2022-02-13 20:32:52 WARNING (MainThread) [custom_components.dahua] Failed to sync device state
Traceback (most recent call last):
  File "/config/custom_components/dahua/__init__.py", line 279, in _async_update_data
    results = await asyncio.gather(*coros)
  File "/config/custom_components/dahua/client.py", line 193, in async_get_config_lighting
    raise e
  File "/config/custom_components/dahua/client.py", line 187, in async_get_config_lighting
    return await self.async_get_config("Lighting[{0}][{1}]".format(channel, profile_mode))
  File "/config/custom_components/dahua/client.py", line 172, in async_get_config
    return await self.get(url)
  File "/config/custom_components/dahua/client.py", line 675, in get
    raise exception
  File "/config/custom_components/dahua/client.py", line 661, in get
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('http://192.168.1.100:80/cgi-bin/configManager.cgi?action=getConfig&name=Lighting%5B0%5D%5B0%5D')
2022-02-13 20:32:52 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 9.445 seconds (success: False)
2022-02-13 20:32:52 INFO (Thread-116) [custom_components.dahua] Hold time: 5
2022-02-13 20:32:52 INFO (Thread-116) [custom_components.dahua] Device Type: VTO2000A
2022-02-13 20:32:52 INFO (Thread-116) [custom_components.dahua] Version: 3.120.000000001.0.R, Build Date: 2019-02-22
2022-02-13 20:32:52 INFO (Thread-116) [custom_components.dahua] Serial Number: 5D09714PAZB4984
2022-02-13 20:32:52 DEBUG (Thread-116) [custom_components.dahua] VTO Data received: {'Action': 'Start', 'Code': 'CallNoAnswered', 'Data': {'CallID': '133', 'LocaleTime': '2022-02-13 20:32:52', 'UTC': 1644784372.0}, 'Index': 9900, 'Param': {'CallID': '133'}, 'deviceType': 'VTO2000A', 'serialNumber': '5D09714PAZB4984', 'DeviceName': '5D09714PAZB4984'}
2022-02-13 20:32:56 DEBUG (Thread-113) [custom_components.dahua] Keep alive
2022-02-13 20:33:21 DEBUG (Thread-114) [custom_components.dahua] Keep alive
2022-02-13 20:33:47 DEBUG (Thread-117) [custom_components.dahua] Keep alive
2022-02-13 20:33:51 DEBUG (Thread-118) [custom_components.dahua] Keep alive
2022-02-13 20:34:16 DEBUG (Thread-119) [custom_components.dahua] Keep alive
2022-02-13 20:34:20 INFO (Thread-123) [custom_components.dahua] Starting DahuaVtoEventThread
2022-02-13 20:34:20 DEBUG (Thread-123) [custom_components.dahua] Connecting to VTO event stream
2022-02-13 20:34:20 DEBUG (Thread-123) [custom_components.dahua] VTO connection established
2022-02-13 20:34:20 DEBUG (Thread-123) [custom_components.dahua] Prepare pre-login message
2022-02-13 20:34:21 DEBUG (Thread-123) [custom_components.dahua] Prepare login message
2022-02-13 20:34:21 INFO (Thread-123) [custom_components.dahua] Get access control configuration
2022-02-13 20:34:21 INFO (Thread-123) [custom_components.dahua] Get version
2022-02-13 20:34:21 INFO (Thread-123) [custom_components.dahua] Get serial number
2022-02-13 20:34:21 INFO (Thread-123) [custom_components.dahua] Get device type
2022-02-13 20:34:21 INFO (Thread-123) [custom_components.dahua] Attach event manager
2022-02-13 20:34:21 INFO (Thread-123) [custom_components.dahua] Serial Number: 5D09714PAZB4984
2022-02-13 20:34:21 INFO (Thread-123) [custom_components.dahua] Version: 3.120.000000001.0.R, Build Date: 2019-02-22
2022-02-13 20:34:21 INFO (Thread-123) [custom_components.dahua] Device Type: VTO2000A
2022-02-13 20:34:21 INFO (Thread-123) [custom_components.dahua] Hold time: 5
2022-02-13 20:34:22 WARNING (MainThread) [custom_components.dahua] Failed to sync device state
Traceback (most recent call last):
  File "/config/custom_components/dahua/__init__.py", line 279, in _async_update_data
    results = await asyncio.gather(*coros)
  File "/config/custom_components/dahua/client.py", line 193, in async_get_config_lighting
    raise e
  File "/config/custom_components/dahua/client.py", line 187, in async_get_config_lighting
    return await self.async_get_config("Lighting[{0}][{1}]".format(channel, profile_mode))
  File "/config/custom_components/dahua/client.py", line 172, in async_get_config
    return await self.get(url)
  File "/config/custom_components/dahua/client.py", line 675, in get
    raise exception
  File "/config/custom_components/dahua/client.py", line 661, in get
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('http://192.168.1.100:80/cgi-bin/configManager.cgi?action=getConfig&name=Lighting%5B0%5D%5B0%5D')
2022-02-13 20:34:22 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 9.940 seconds (success: False)
2022-02-13 20:34:22 DEBUG (Thread-123) [custom_components.dahua] VTO Data received: {'Action': 'Start', 'Code': 'CallNoAnswered', 'Data': {'CallID': '133', 'LocaleTime': '2022-02-13 20:34:21', 'UTC': 1644784461.0}, 'Index': 9900, 'Param': {'CallID': '133'}, 'serialNumber': '5D09714PAZB4984', 'deviceType': 'VTO2000A', 'DeviceName': '5D09714PAZB4984'}
```

**Comment by rroller** [comment]
I released https://github.com/rroller/dahua/releases/tag/0.9.37

Can you try that?

**Comment by si458** [comment]
Thanks @rroller that does seem to fix the issue!
I have slow video feed though and the snapshots take a while to load on the card
But it works! (I'm running on a 3b+ so not the fastest)
Now time to play with the events, I've never tried them before!

**Comment by rroller** [comment]
Nice! Resolving.
