### ISSUE TITLE
Failed to sync device state

### ISSUE THREAD

**Issue by otello86** [rroller/dahua#157]
## Version of the custom_component
Dahua add-on 0.9.36

## Configuration
Home Assistant OS 7.3
Home Assistant 2022.2.3
supervisor-2022.01.1

## Describe the bug
I have add the Dahua integration and config my 4 cameras. All works fine except sometimes the motion of 2 cameras wich crashed, and retry.
I found a lot of error logs "Failed to sync device state" : 2563 currency in 1 day

## Debug log
Failed to sync device state
Traceback (most recent call last):
  File "/config/custom_components/dahua/__init__.py", line 279, in _async_update_data
    results = await asyncio.gather(*coros)
  File "/config/custom_components/dahua/client.py", line 193, in async_get_config_lighting
    raise e
  File "/config/custom_components/dahua/client.py", line 187, in async_get_config_lighting
    return await self.async_get_config("Lighting[{0}][{1}]".format(channel, profile_mode))
  File "/config/custom_components/dahua/client.py", line 172, in async_get_config
    return await self.get(url)
  File "/config/custom_components/dahua/client.py", line 675, in get
    raise exception
  File "/config/custom_components/dahua/client.py", line 661, in get
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('http://192.168.31.41:80/cgi-bin/configManager.cgi?action=getConfig&name=Lighting%5B0%5D%5B0%5D')

**Comment by rroller** [comment]
What model camera is this? So it works sometimes but other times not?

It's interesting that the result is a 500 error from the device. Not sure what I can do about that.

I'm cleaning up the logs so at least you won't have a giant useless stack trace in the logs

**Comment by rroller** [comment]
Logging updated in https://github.com/rroller/dahua/releases/tag/0.9.37

Please update

**Comment by rroller** [comment]
Please feel free to reopen if you still have issues.

**Comment by otello86** [comment]
Hi,
sorry i'm on holidays
I have 4 dahua's camera at home and two of them have this problem. It is the same model : IPC-HFW4431R-Z
The 2 others works correctly
