### ISSUE TITLE
Errors and warnings on restart

### ISSUE THREAD

**Issue by tomlut** [rroller/dahua#158]
## Version of the custom_component

0.9.36 (HACS), or 0.5.0 (const.py), does this need updating?

## Configuration

```yaml

Add your logs here.

This error originated from a custom integration.

Logger: custom_components.dahua
Source: custom_components/dahua/client.py:671
Integration: Dahua (documentation, issues)
First occurred: 11:52:37 (6 occurrences)
Last logged: 11:53:42

TimeoutError fetching information from http://10.1.1.240:80/cgi-bin/configManager.cgi?action=getConfig&name=General -
TimeoutError fetching information from http://10.1.1.240:80/cgi-bin/magicBox.cgi?action=getSystemInfo -
TimeoutError fetching information from http://10.1.1.240:80/cgi-bin/coaxialControlIO.cgi?action=getStatus&channel=1 -
TimeoutError fetching information from http://10.1.1.240:80/cgi-bin/configManager.cgi?action=getConfig&name=Lighting[3][0] -
TimeoutError fetching information from http://10.1.1.240:80/cgi-bin/configManager.cgi?action=getConfig&name=Lighting[4][0] -
```
```yaml
Logger: homeassistant.config_entries
Source: config_entries.py:358
First occurred: 11:52:37 (2 occurrences)
Last logged: 11:52:38

Config entry 'Workshop Camera' for dahua integration not ready yet; Retrying in background
Config entry 'Front Camera' for dahua integration not ready yet; Retrying in background
```
```yaml
This error originated from a custom integration.

Logger: custom_components.dahua
Source: custom_components/dahua/__init__.py:188
Integration: Dahua (documentation, issues)
First occurred: 11:52:37 (2 occurrences)
Last logged: 11:52:38

Failed to sync device state
Traceback (most recent call last):
  File "/config/custom_components/dahua/__init__.py", line 188, in _async_update_data
    data.update(response)
TypeError: 'NoneType' object is not iterable


```

## Describe the bug
I am receiving the above warnings and errors for the dahua integration after every home assistant restart. Everything seems to be functioning correctly though. The camera that times out changes with each restart. 

Cameras (7 of): DH-IPC-HDW3841EMP-AS-0280B (can probably be added to the compatible 8MP camera list)

NVR: DHI-NVR5208-8P-4KS2 (can probably be added to the compatible NVR list)

## Debug log

```text

2022-02-09 11:52:20 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration astroweather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-09 11:52:20 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-09 11:52:20 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration bureau_of_meteorology which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-09 11:52:20 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dahua which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-09 11:52:20 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration weatherflow which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-09 11:52:20 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration garbage_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-09 11:52:20 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-09 11:52:20 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-09 11:52:37 ERROR (MainThread) [custom_components.dahua] TimeoutError fetching information from http://10.1.1.240:80/cgi-bin/configManager.cgi?action=getConfig&name=General -
2022-02-09 11:52:37 WARNING (MainThread) [custom_components.dahua] Failed to sync device state
Traceback (most recent call last):
File "/config/custom_components/dahua/__init__.py", line 188, in _async_update_data
data.update(response)
TypeError: 'NoneType' object is not iterable
2022-02-09 11:52:37 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 13.858 seconds (success: False)
2022-02-09 11:52:37 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Workshop Camera' for dahua integration not ready yet; Retrying in background
2022-02-09 11:52:38 ERROR (MainThread) [custom_components.dahua] TimeoutError fetching information from http://10.1.1.240:80/cgi-bin/magicBox.cgi?action=getSystemInfo -
2022-02-09 11:52:38 ERROR (MainThread) [custom_components.dahua] TimeoutError fetching information from http://10.1.1.240:80/cgi-bin/configManager.cgi?action=getConfig&name=General -
2022-02-09 11:52:38 WARNING (MainThread) [custom_components.dahua] Failed to sync device state
Traceback (most recent call last):
File "/config/custom_components/dahua/__init__.py", line 188, in _async_update_data
data.update(response)
TypeError: 'NoneType' object is not iterable
2022-02-09 11:52:38 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 14.393 seconds (success: False)
2022-02-09 11:52:38 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Front Camera' for dahua integration not ready yet; Retrying in background
2022-02-09 11:52:39 ERROR (MainThread) [custom_components.dahua] TimeoutError fetching information from http://10.1.1.240:80/cgi-bin/coaxialControlIO.cgi?action=getStatus&channel=1 -
2022-02-09 11:52:41 INFO (Thread-12) [custom_components.dahua] Starting DahuaEventThread
2022-02-09 11:52:43 INFO (Thread-14) [custom_components.dahua] Starting DahuaEventThread
2022-02-09 11:52:43 INFO (Thread-10) [custom_components.dahua] Starting DahuaEventThread
2022-02-09 11:52:43 INFO (Thread-8) [custom_components.dahua] Starting DahuaEventThread
2022-02-09 11:52:45 INFO (Thread-6) [custom_components.dahua] Starting DahuaEventThread
2022-02-09 11:52:54 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 31.060 seconds (success: True)
2022-02-09 11:52:56 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 32.686 seconds (success: True)
2022-02-09 11:52:57 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 33.631 seconds (success: True)
2022-02-09 11:52:59 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 35.771 seconds (success: True)
2022-02-09 11:53:01 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 37.358 seconds (success: True)
2022-02-09 11:53:10 INFO (Thread-23) [custom_components.dahua] Starting DahuaEventThread
2022-02-09 11:53:11 INFO (Thread-21) [custom_components.dahua] Starting DahuaEventThread
2022-02-09 11:53:15 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 11.778 seconds (success: True)
2022-02-09 11:53:18 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 13.947 seconds (success: True)
2022-02-09 11:53:36 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 5.032 seconds (success: True)
2022-02-09 11:53:37 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 6.139 seconds (success: True)
2022-02-09 11:53:39 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 8.657 seconds (success: True)
2022-02-09 11:53:42 ERROR (MainThread) [custom_components.dahua] TimeoutError fetching information from http://10.1.1.240:80/cgi-bin/configManager.cgi?action=getConfig&name=Lighting[3][0] -
2022-02-09 11:53:42 ERROR (MainThread) [custom_components.dahua] TimeoutError fetching information from http://10.1.1.240:80/cgi-bin/configManager.cgi?action=getConfig&name=Lighting[4][0] -
2022-02-09 11:53:42 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 11.125 seconds (success: True)
2022-02-09 11:53:42 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 11.126 seconds (success: True)
2022-02-09 11:53:48 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 3.382 seconds (success: True)
2022-02-09 11:53:51 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 3.004 seconds (success: True)
2022-02-09 11:54:09 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 3.339 seconds (success: True)
2022-02-09 11:54:11 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 4.512 seconds (success: True)
2022-02-09 11:54:13 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 4.510 seconds (success: True)

```

**Comment by rroller** [comment]
I can guard against the "TypeError: 'NoneType' object is not iterable" but not sure that I can do anything about he timeout. 
I might see about extending the timeouts...

**Comment by rroller** [comment]
Updated in https://github.com/rroller/dahua/releases/tag/0.9.37

Please give that a try

**Comment by tomlut** [comment]
The start up errors are gone. Thanks Ronnie.
