### ISSUE TITLE
VTO2202F-P

### ISSUE THREAD

**Issue by cagnulein** [rroller/dahua#187]
I can't connect to my VTO. I guess the main issue is that is redirecting to 443?
I installed your plugin from HACS

This error originated from a custom integration.

Logger: custom_components.dahua
Source: custom_components/dahua/client.py:670
Integration: Dahua (documentation, issues)
First occurred: 11:49:59 AM (2 occurrences)
Last logged: 11:52:13 AM

Could not connect to Dahua device. For iMou devices see https://github.com/rroller/dahua/issues/6
Traceback (most recent call last):
  File "/config/custom_components/dahua/config_flow.py", line 177, in _test_credentials
    data = await client.get_machine_name()
  File "/config/custom_components/dahua/client.py", line 101, in get_machine_name
    return await self.get("/cgi-bin/magicBox.cgi?action=getMachineName")
  File "/config/custom_components/dahua/client.py", line 687, in get
    raise exception
  File "/config/custom_components/dahua/client.py", line 670, in get
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://192.168.0.108:443/cgi-bin/magicBox.cgi?action=getMachineName')

**Comment by cagnulein** [comment]
auto solved disabling HTTPS from the VTO admin page
