### ISSUE TITLE
Object is not subscriptable

### ISSUE THREAD

**Issue by pepe59** [rroller/dahua#19]
An error appears in the log after the last update.

This error comes from the integration itself.

Logger: homeassistant.config_entries
Source: custom_components/dahua/binary_sensor.py:16
Integration: Dahua (documentation, issues)
First occurred: 20:04:41 (1 occurrences)
Last logged: 20:04:41

Error setting up entry Kamera-ALM for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 141, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 149, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 328, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/dahua/binary_sensor.py", line 16, in <module>
    NAME_OVERRIDES: dict[str, str] = {
TypeError: 'type' object is not subscriptable

**Comment by rroller** [comment]
Thanks. Taking a look.

**Comment by rroller** [comment]
@pepe59 what version of Home Assistant are you on? Do you have an older version of python?

**Comment by rroller** [comment]
@pepe59 can you upgrade to 0.6.1 and see if that corrects the problem for you?

https://github.com/rroller/dahua/releases/tag/0.6.1

**Comment by rroller** [comment]
Made one more update to 0.6.2

**Comment by pepe59** [comment]
I have the HA core-2021.6.5 version
I upgraded to version 0.6.2 and after restart the error no longer appears and new 3 entities have been created. I'm going to have to see how all entities work.
Thanks for the repair

**Comment by rroller** [comment]
Awesome, thanks. Please reopen if you have this issue again.
