### ISSUE TITLE
Only a single instance of a device is allowed.

### ISSUE THREAD

**Issue by RexS98** [rroller/dahua#270]
Got 3 camera works all good. 
Today add new successful, but trying to re-add and reduce some unused sensors. 
After remove the device and re-add with same config. 
It shows "Only a single instance of a device is allowed."
But actuallt even when I add a camera already exist it will not stop doing that. 

Anyone know how can I re-add the camera.
```
Logger: aiohttp.server
Source: custom_components/dahua/digest.py:46
Integration: Dahua (documentation, issues)
First occurred: 23:02:19 (6 occurrences)
Last logged: 23:04:26

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 734, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 752, in handle
    image = await _async_get_image(
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 171, in _async_get_image
    if image_bytes := await camera.async_camera_image(
  File "/config/custom_components/dahua/camera.py", line 233, in async_camera_image
    return await self._coordinator.client.async_get_snapshot(self._channel_number)
  File "/config/custom_components/dahua/client.py", line 74, in async_get_snapshot
    return await self.get_bytes(url)
  File "/config/custom_components/dahua/client.py", line 721, in get_bytes
    response = await auth.request("GET", self._base + url)
  File "/config/custom_components/dahua/digest.py", line 50, in request
    return await self._handle_401(response)
  File "/config/custom_components/dahua/digest.py", line 151, in _handle_401
    return await self.request(
  File "/config/custom_components/dahua/digest.py", line 46, in request
    response = await self.session.request(method, url, headers=headers, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

**Comment by sasukebinbin** [comment]
I give up and change to use nodered

**Comment by zios0007** [comment]
That abort cannot happen on a current version. The check is commented out:

`custom_components/dahua/config_flow.py`

```python
# if self._async_current_entries():
#     return self.async_abort(reason="single_instance_allowed")
```

What can still stop a re-add is the genuine duplicate check, which is per device and per channel rather than one instance overall, and it says "already configured" rather than "only a single instance is allowed".

One thing behind some of these reports was real and is fixed: two devices behind one address on different ports, say a bridge forwarding 80 to one camera and 81 to another, shared a cache keyed on the address alone, so the second device was served the first one's identity (#664). That produced devices getting mixed up after a restart and re-adds behaving strangely.

@yvesdemoerloose @RexS98 worth another go on a current version. If a re-add is still refused, the exact abort message matters, because the three of them mean different things.

@rroller closeable unless someone reproduces it on current code.
