### ISSUE TITLE
Snapshots have become unreliable

### ISSUE THREAD

**Issue by hole222** [rroller/dahua#290]
After years of reliable service from this integration the snapshot service is now intermittently failing:
```
This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/dahua/client.py:731 
Integration: Dahua 
First occurred: 2 July 2023 at 09:27:18 (2 occurrences) 
Last logged: 14:18:19

Error executing service: <ServiceCall camera.snapshot (c:01H4A6SJ8F7EWHZ8VX8SBQS8KS): entity_id=['camera.front_camera_sub_2'], filename=Template<template=(/config/www/snapshots/front_door.jpg) renders=1>>
Error executing service: <ServiceCall camera.snapshot (c:01H4D9V3Y2Z0YANPH4F6VBYFB4): entity_id=['camera.front_camera_sub_2'], filename=Template<template=(/config/www/snapshots/front_door.jpg) renders=1>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1928, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 930, in async_handle_snapshot_service
    image = await camera.async_camera_image()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dahua/camera.py", line 243, in async_camera_image
    return await self._coordinator.client.async_get_snapshot(self._channel_number)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dahua/client.py", line 74, in async_get_snapshot
    return await self.get_bytes(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dahua/client.py", line 731, in get_bytes
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('http://10.1.1.240:80/cgi-bin/snapshot.cgi?channel=1')
```

Home Assistant 2023.6.3
Supervisor 2023.06.4
Operating System 10.3
Frontend 20230608.0 - latest
Dahua Integration 0.9.47

**Comment by parautenbach** [comment]
If been trying all sorts of workarounds because of this bug and finally thought to see if it's already been reported. I'm using the built-in Dahua integration with my Amcrest doorbell. 

```
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1083, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 1041, in async_handle_snapshot_service
    else await camera.async_camera_image()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dahua/camera.py", line 253, in async_camera_image
    return await self._coordinator.client.async_get_snapshot(self._channel_number)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dahua/client.py", line 75, in async_get_snapshot
    return await self.get_bytes(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dahua/client.py", line 780, in get_bytes
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 629, in raise_for_status
    raise ClientResponseError(
    ...<5 lines>...
    )
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url='http://doorbell/cgi-bin/snapshot.cgi?channel=1'
```

```
automation:
  - alias: "Notify If Doorbell Rang"
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.doorbell_rang
        to: "on"
    mode: queued
    action:
      ...
      - service: script.take_snapshot
         data:
         camera_entity: camera.doorbell
           subdirectory: "doorbell"
         continue_on_error: true
      ...
```

```
  take_snapshot:
    fields:
      camera_entity:
        description: "A camera entity"
        example: "camera.my_camera"
      subdirectory:
        description: "The subdirectory under www/gallery/ to write the snapshot to."
        example: "my_subdirectory"
    mode: queued
    sequence:
      - variables:
          timestamp: "{{ now().strftime('%Y%m%d-%H%M%S') }}"
          filename: "/config/www/gallery/{{ subdirectory }}/{{ camera_entity }}_{{ timestamp }}.jpg"
      - service: camera.snapshot
        target:
          entity_id: "{{ camera_entity }}"
        data:
          filename: "{{ filename }}"
      - service: shell_command.copy_last_snapshot_image
        data:
          subdirectory: "{{ subdirectory }}"
          camera_entity: "{{ camera_entity }}"
```

**Comment by parautenbach** [comment]
I see no appropriate error handling for this issue here:

https://github.com/rroller/dahua/blob/c787e51885cf3037cc8abe0a67f4a17cabcc887f/custom_components/dahua/camera.py#L258

https://github.com/rroller/dahua/blob/c787e51885cf3037cc8abe0a67f4a17cabcc887f/custom_components/dahua/__init__.py#L222

https://github.com/rroller/dahua/blob/c787e51885cf3037cc8abe0a67f4a17cabcc887f/custom_components/dahua/client.py#L67

If the maintainer(s) can indicate where they think it would be best to handle this, I'd be happy to submit a PR when I have some time. Whatever the case, it should be done in such a way that it would allow HA to continue when the `continue_on_error: true` setting is used on a service (action) call (if one wishes for that behaviour). From what I read, it means the code must raise a `HomeAssistantError`.

**Comment by zios0007** [comment]
@parautenbach you are right, and you pointed at the exact line. This is still unfixed and I have opened #758 for it.

`async_camera_image` passes the snapshot straight through:

```python
async def async_camera_image(self, width=None, height=None):
    return await self._coordinator.client.async_get_snapshot(self._channel_number)
```

so a transient refusal from the camera, which these devices do under load, comes out of `camera.snapshot` as a service error rather than as a snapshot that did not happen. Recorders are especially prone to it, since every channel is competing for the same device.

Two things reduce how often it happens, and neither makes the error handling unnecessary: reads are shared per host now, so ten channels no longer produce ten simultaneous requests, and the snapshot path no longer pulls a full image where it only needs a status.

#758 returns `None` on a transport failure, which is what Home Assistant expects and what every other camera integration does, and logs it rather than raising into whatever called it.
