### ISSUE TITLE
Last update not working. Missing Camera device.

### ISSUE THREAD

**Issue by TheDukeSr** [rroller/dahua#30]
v0.8.1. was working perfect.

Updated to 0.8.3.
First Reboot>> Error in log: Camera not found.
2nd Reboot>> No error, but also NO camera device!

Removed Camera, and RE-added camera.
Camera device still missing.

Back to v0.8.1. >> All working prefectly.

## Debug log
```
2021-06-26 09:26:33 DEBUG (Thread-3) [custom_components.dahua] Starting DahuaEventThread
2021-06-26 09:26:33 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 2.410 seconds
2021-06-26 09:27:03 DEBUG (Thread-18) [custom_components.dahua] Starting DahuaEventThread
2021-06-26 09:27:04 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 1.756 seconds
2021-06-26 09:27:15 DEBUG (Thread-20) [custom_components.dahua] Starting DahuaEventThread
2021-06-26 09:27:15 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 1.775 seconds
2021-06-26 09:27:28 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: Camera not found
2021-06-26 09:27:36 DEBUG (Thread-23) [custom_components.dahua] Starting DahuaEventThread
```
Also text at integration: **Retrying setup**
[Screenprint Integration Screen](https://photos.app.goo.gl/GMmfKF9umaiF6QRa8)
```

**Comment by rroller** [comment]
Thank you for reporting this. What model camera is it?

**Comment by TheDukeSr** [comment]
IPC-HDW4233C-A

Standard IP Cam.

**Comment by rroller** [comment]
Are you certain you are 0.8.3? I can't reproduce this with similar cams. Anything else in the logs? There's one possible bug that might exist. I'll put in a fix for that and report back soon.

**Comment by rroller** [comment]
I just released 0.8.4 as an attempt to prevent this issue based on the only changed made in 0.8.3.

I believe your camera might not have the day/night profile mode API.

**Comment by TheDukeSr** [comment]
Confirmed problem appeared from 0.8.1 >>> 0.8.2 (see below)

Info setup: Settings not changed, just updated versions with HACS.

**0.8.4.**
**not working.** 

Same config back to **0.8.3**
Result: **Not working**

Same config back to **0.8.2**
Result: **Not working**

Same config back to 0.8.1
Result: **100% OK !**

So please have a look at differences between .1 >> .2  


Latest log 0.8.4 :
``` 
2021-06-27 19:56:42 DEBUG (Thread-3) [custom_components.dahua] Starting DahuaEventThread
2021-06-27 19:56:42 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 1.716 seconds
2021-06-27 19:57:30 DEBUG (Thread-18) [custom_components.dahua] Starting DahuaEventThread
2021-06-27 19:57:31 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 1.768 seconds
2021-06-27 19:57:42 DEBUG (Thread-20) [custom_components.dahua] Starting DahuaEventThread
2021-06-27 19:57:42 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 1.397 seconds
2021-06-27 19:57:52 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: Camera not found
2021-06-27 19:58:03 DEBUG (Thread-22) [custom_components.dahua] Starting DahuaEventThread
2021-06-27 19:58:04 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 1.262 seconds

```

**Comment by TheDukeSr** [comment]
If there's something I can do just tell me.
Maybe a small script or commands to run and find API commands from the cam?
Just let me know, I'll try to help.

**Comment by rroller** [comment]
Digging into this. Here's the diff between those two versions...
https://github.com/rroller/dahua/compare/0.8.1...0.8.2

**Comment by rroller** [comment]
What happens when you call this API for your camera?

```
http://YOUR_IP_ADDRESS/cgi-bin/configManager.cgi?action=getConfig&name=VideoInMode
```

**Comment by rroller** [comment]
You can try 0.8.5. It broadens the errors it catches. I dont' think that'll fix your issue. Once we get the API output from the following I think we'll know more...

```
http://YOUR_IP_ADDRESS/cgi-bin/configManager.cgi?action=getConfig&name=VideoInMode
````

https://github.com/rroller/dahua/releases/tag/0.8.5

**Comment by TheDukeSr** [comment]
> http://YOUR_IP_ADDRESS/cgi-bin/configManager.cgi?action=getConfig&name=VideoInMode

Result:
```
table.VideoInMode[0].Config[0]=2
table.VideoInMode[0].Mode=0
table.VideoInMode[0].TimeSection[0][0]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[0][1]=0 00:00:00-23:59:59
table.VideoInMode[0].TimeSection[0][2]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[0][3]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[0][4]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[0][5]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[1][0]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[1][1]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[1][2]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[1][3]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[1][4]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[1][5]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[2][0]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[2][1]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[2][2]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[2][3]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[2][4]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[2][5]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[3][0]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[3][1]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[3][2]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[3][3]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[3][4]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[3][5]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[4][0]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[4][1]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[4][2]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[4][3]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[4][4]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[4][5]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[5][0]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[5][1]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[5][2]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[5][3]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[5][4]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[5][5]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[6][0]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[6][1]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[6][2]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[6][3]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[6][4]=0 00:00:00-24:00:00
table.VideoInMode[0].TimeSection[6][5]=0 00:00:00-24:00:00
```

**Comment by TheDukeSr** [comment]
v .5 result: Not good.

```
2021-06-27 22:29:07 DEBUG (Thread-3) [custom_components.dahua] Starting DahuaEventThread
2021-06-27 22:29:07 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 2.186 seconds
2021-06-27 22:29:44 DEBUG (Thread-17) [custom_components.dahua] Starting DahuaEventThread
2021-06-27 22:29:44 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 1.589 seconds
2021-06-27 22:29:54 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: Camera not found
2021-06-27 22:29:55 DEBUG (Thread-19) [custom_components.dahua] Starting DahuaEventThread
2021-06-27 22:29:56 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 1.590 seconds

```

**Comment by rroller** [comment]
Nice, that API output helped. 
```
table.VideoInMode[0].Config[0]=2
```

2=scene mode or "general" mode. 0=day, 1=night. I haven't experimented with 2 before. This gives me something good to work on. I'll report back once I know more. Thanks!

**Comment by rroller** [comment]
I can't reproduce the error when in profile mode 2.

In 0.8.6 I've added extra logging that should capture update failures. Can you please upgrade to https://github.com/rroller/dahua/releases/tag/0.8.6 and paste the logs you get, Thanks!

**Comment by TheDukeSr** [comment]
ps. You've got Email ;)

Here we go.. Update and Restart # 352... lol

```
2021-06-27 22:59:23 DEBUG (Thread-3) [custom_components.dahua] Starting DahuaEventThread
2021-06-27 22:59:24 WARNING (MainThread) [custom_components.dahua] Failed to sync device state
Traceback (most recent call last):
File "/config/custom_components/dahua/__init__.py", line 211, in _async_update_data
results = await asyncio.gather(*coros)
File "/config/custom_components/dahua/client.py", line 213, in async_common_config
return await self.api_wrapper("get", url, headers=HEADERS)
File "/config/custom_components/dahua/client.py", line 570, in api_wrapper
raise exception
File "/config/custom_components/dahua/client.py", line 552, in api_wrapper
response.raise_for_status()
File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('http://LOCALIPNR:80/cgi-bin/configManager.cgi?action=getConfig&name=MotionDetect&action=getConfig&name=Lighting%5B0%5D%5B2%5D')
2021-06-27 22:59:24 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 2.027 seconds
2021-06-27 22:59:47 DEBUG (Thread-11) [custom_components.dahua] Starting DahuaEventThread
2021-06-27 22:59:48 WARNING (MainThread) [custom_components.dahua] Failed to sync device state
Traceback (most recent call last):
File "/config/custom_components/dahua/__init__.py", line 211, in _async_update_data
results = await asyncio.gather(*coros)
File "/config/custom_components/dahua/client.py", line 213, in async_common_config
return await self.api_wrapper("get", url, headers=HEADERS)
File "/config/custom_components/dahua/client.py", line 570, in api_wrapper
raise exception
File "/config/custom_components/dahua/client.py", line 552, in api_wrapper
response.raise_for_status()
File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('http://LOCALIPNR:80/cgi-bin/configManager.cgi?action=getConfig&name=MotionDetect&action=getConfig&name=Lighting%5B0%5D%5B2%5D')
2021-06-27 22:59:48 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 2.117 seconds
2021-06-27 23:00:00 DEBUG (Thread-19) [custom_components.dahua] Starting DahuaEventThread
2021-06-27 23:00:01 WARNING (MainThread) [custom_components.dahua] Failed to sync device state
Traceback (most recent call last):
File "/config/custom_components/dahua/__init__.py", line 211, in _async_update_data
results = await asyncio.gather(*coros)
File "/config/custom_components/dahua/client.py", line 213, in async_common_config
return await self.api_wrapper("get", url, headers=HEADERS)
File "/config/custom_components/dahua/client.py", line 570, in api_wrapper
raise exception
File "/config/custom_components/dahua/client.py", line 552, in api_wrapper
response.raise_for_status()
File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('http://LOCALIPNR:80/cgi-bin/configManager.cgi?action=getConfig&name=MotionDetect&action=getConfig&name=Lighting%5B0%5D%5B2%5D')
2021-06-27 23:00:01 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 3.477 seconds

```

**Comment by rroller** [comment]
Weird, this is failing with your camera... 

```
http://YOUR_IP_ADDRESS/cgi-bin/configManager.cgi?action=getConfig&name=MotionDetect&action=getConfig&name=Lighting[0][2]
```

I assume the `2` in the URL is what's doing it since that is what changed in the breaking version. Very odd that I can't reproduce this with any of my cameras

**Comment by rroller** [comment]
Oh wow, I just reproduced the issue. Doing more digging and I'll report back.

**Comment by TheDukeSr** [comment]
> Weird, this is failing with your camera...
> 
> ```
> http://YOUR_IP_ADDRESS/cgi-bin/configManager.cgi?action=getConfig&name=MotionDetect&action=getConfig&name=Lighting[0][2]
> ```
> 
> I assume the `2` in the URL is what's doing it since that is what changed in the breaking version. Very odd that I can't reproduce this with any of my cameras

Yup, confirmed it's that nr 2.

http://IP/cgi-bin/configManager.cgi?action=getConfig&name=MotionDetect&action=getConfig&name=Lighting[0][0]
Result OK

http://IP/cgi-bin/configManager.cgi?action=getConfig&name=MotionDetect&action=getConfig&name=Lighting[0][2]
Bad Request.

**Comment by rroller** [comment]
0.8.7 is now released which should fix this for your camera. Please give it a try and let me know, thanks!

https://github.com/rroller/dahua/releases/tag/0.8.7

**Comment by TheDukeSr** [comment]
You GOT IT !!!
Thnx, great work.
Cam is back.

If you ever need more debugging for cams of this type, you know where to find me.

Log:
```
2021-06-28 00:10:39 DEBUG (Thread-3) [custom_components.dahua] Starting DahuaEventThread
2021-06-28 00:10:39 WARNING (MainThread) [custom_components.dahua] Cam does not support profile mode. Will use mode 0
2021-06-28 00:10:40 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 1.353 seconds
2021-06-28 00:11:21 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 0.162 seconds
2021-06-28 00:11:51 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 0.148 seconds
2021-06-28 00:12:21 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 0.135 seconds
2021-06-28 00:12:51 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 0.147 seconds
2021-06-28 00:13:21 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 0.160 seconds
2021-06-28 00:13:51 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 0.157 seconds
2021-06-28 00:14:21 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 0.268 seconds
2021-06-28 00:14:51 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 0.161 seconds
2021-06-28 00:15:21 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 0.134 seconds
2021-06-28 00:15:39 DEBUG (Thread-3) [custom_components.dahua]
2021-06-28 00:15:39 DEBUG (Thread-3) [custom_components.dahua] reconnecting to camera's event stream...

```

**Comment by rroller** [comment]
Thanks for sticking with it and all the help!
