### ISSUE TITLE
Dahua camera model DH-IPC-HDW3641EM-S-S2

### ISSUE THREAD

**Issue by jeffm999** [rroller/dahua#330]
cannot connect integration to ip camera model **DH-IPC-HDW3641EM-S-S2**

is this 6MP camera supported?

using latest firmware - V2.820.0000000.28.R.230314

credentials are correct, camera is operating correctly

**Comment by stalniy** [comment]
From what I found, at least for live streaming, password was not urlencoded. This was the reason why my live video didn’t work

but you need to do is to enable debug logging for dahua in HA and then check/share logs

**Comment by jeffm999** [comment]
this is HA error log entry after installation attempt:
```
This error originated from a custom integration.
Logger: custom_components.dahua
Source: custom_components/dahua/config_flow.py:188
Integration: dahua (documentation, issues)
First occurred: 21:51:14 (3 occurrences)
Last logged: 21:55:11

Could not connect to Dahua device. For iMou devices see https://github.com/rroller/dahua/issues/6
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1173, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 884, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -5] Name has no usable address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/dahua/config_flow.py", line 188, in _test_credentials
    data = await client.get_machine_name()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dahua/client.py", line 121, in get_machine_name
    return await self.get("/cgi-bin/magicBox.cgi?action=getMachineName")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dahua/client.py", line 792, in get
    raise exception
  File "/config/custom_components/dahua/client.py", line 774, in get
    response = await auth.request("GET", url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dahua/digest.py", line 46, in request
    response = await self.session.request(method, url, headers=headers, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 574, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1187, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host http:80 ssl:default [Name has no usable address]
```

**Comment by stalniy** [comment]
Seems like DNS issue, what do you enter in Address field?

**Comment by JimGermany** [comment]
More (network) info pls.

Example setting in WebGUI
![Dahua_Netzwerk](https://github.com/rroller/dahua/assets/96919423/ba1574e8-bfae-4c3d-8a64-bca06a1e1b45)

Camera IP and URL to call the WebGUI?
HA IP? 
Router IP? 
Is there a firewall or firewall settings somewhere that could potentially block access?
IPv4 or IPv6?

**Comment by jeffm999** [comment]
here is camera IP settings :
![dahua2](https://github.com/rroller/dahua/assets/49336389/bb6a4b7f-f559-4783-904a-e9a8823d4682)

I can ping the camera ip from HA terminal. no firewall involved as all is on LAN.

in the integration address field , I enter the camera LAN address 192.168.0.8.

in HA I can connect with MJPEG IP Camera integration and view camera image.

**Comment by JimGermany** [comment]
OK, that looks and sounds to me like everything is set up correctly. Unfortunately I have no idea why this error message _(Cannot connect to host http:80 ssl:default [Name has no usable address])_ occurs. Maybe it has something to do with how the camera is addressed via API, but only rroller will probably be able to say something about that.

As an alternative, if you haven't already done so, you can integrate the camera via Onvif integration. Please note the Onvif settings in the camera's WebGUI and/or set them accordingly.

**Comment by jeffm999** [comment]
factory reset camera and after a while connection to integration is possible, but with the following warning in logfile :+1: 

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1524
First occurred: 10:50:56 (3 occurrences)
Last logged: 10:50:56

Entity camera.7c0b42bpagdca55_main (<class 'custom_components.dahua.camera.DahuaCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.STREAM: 2>, please create a bug report at https://github.com/rroller/dahua/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
Entity camera.7c0b42bpagdca55_sub (<class 'custom_components.dahua.camera.DahuaCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.STREAM: 2>, please create a bug report at https://github.com/rroller/dahua/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
Entity camera.7c0b42bpagdca55_sub_2 (<class 'custom_components.dahua.camera.DahuaCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.STREAM: 2>, please create a bug report at https://github.com/rroller/dahua/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
```
