### ISSUE TITLE
IPC-HDBW5421E-Z Working & IPC-HDBW2320R-ZS Not Working

### ISSUE THREAD

**Issue by 2wenty2wo** [rroller/dahua#34]
Hi,

**Confirmed working:**
IPC-HDBW5421E-Z

**Not working:**
IPC-HDBW2320R-ZS
Says "_Username, Password, or Address is wrong_". Which it isn't.

Not sure if it's just not supported or if something else is wrong?

Thanks

**Comment by JLFN** [comment]
Its same login that you use for webinterface.
https://ipcamtalk.com/attachments/
[Amcrest+HTTP+API+9.2020.pdf](https://github.com/rroller/dahua/files/6724391/Amcrest%2BHTTP%2BAPI%2B9.2020.pdf)
for-ipcamtalk-_com-pdf.61808/

**Comment by 2wenty2wo** [comment]
I can log into the web interface of the camera with the same credentials yet it says it's wrong in the integration setup.

**Comment by rroller** [comment]
@2wenty2wo can you look in the logs and find out what the message is? That should disclose the actual error. Thanks!

**Comment by rroller** [comment]
Also, I believe that mini-dome style camera has a different API and won't work until this issue is resolved - https://github.com/rroller/dahua/issues/6

**Comment by 2wenty2wo** [comment]
This is the error I'm getting: 401 Unauthorized. 
        
    Logger: custom_components.dahua
    Source: custom_components/dahua/client.py:576
    Integration: Dahua (documentation, issues)
    First occurred: 12:43:14 AM (1 occurrences)
    Last logged: 12:43:14 AM
    
    Could not connect to Dahua device
    Traceback (most recent call last):
      File "/config/custom_components/dahua/config_flow.py", line 178, in _test_credentials
        data = await client.get_machine_name()
      File "/config/custom_components/dahua/client.py", line 128, in get_machine_name
        return await self.api_wrapper("get", url, headers=HEADERS)
      File "/config/custom_components/dahua/client.py", line 594, in api_wrapper
        raise exception
      File "/config/custom_components/dahua/client.py", line 576, in api_wrapper
        response.raise_for_status()
      File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
        raise ClientResponseError(
    aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url=URL('xxxxxxxxxxxxxxx/cgi-bin/magicBox.cgi?action=getMachineName')

**Comment by rroller** [comment]
Interesting. And I assume you've verified you are using the correct username and password? I believe this is just the same issue as the other dome style cameras... they use a different API. You can follow along in https://github.com/rroller/dahua/issues/6 as to when I get this fixed.

**Comment by 2wenty2wo** [comment]
Yes I’ve confirmed the credentials multiple times trying to prove myself wrong. I guess it could be an API problem. I’ve subscribed to that thread to follow along. Thank you.

**Comment by paalj69** [comment]
I get the same error from my IPC-HFW2100P:
Denne feilen stammer fra en tilpasset integrasjon.

Logger: custom_components.dahua
Source: custom_components/dahua/client.py:576
Integration: Dahua (documentation, issues)
First occurred: 6:48:40 (2 occurrences)
Last logged: 6:56:16

Could not connect to Dahua device
Traceback (most recent call last):
  File "/config/custom_components/dahua/config_flow.py", line 178, in _test_credentials
    data = await client.get_machine_name()
  File "/config/custom_components/dahua/client.py", line 128, in get_machine_name
    return await self.api_wrapper("get", url, headers=HEADERS)
  File "/config/custom_components/dahua/client.py", line 594, in api_wrapper
    raise exception
  File "/config/custom_components/dahua/client.py", line 576, in api_wrapper
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url=URL('http://xxxxxxxxxx:80/cgi-bin/magicBox.cgi?action=getMachineName')

**Comment by paalj69** [comment]
With the latest 0.8.13 on Dahua IPC-HFW2100P I get this:
Denne feilen stammer fra en tilpasset integrasjon.

Logger: custom_components.dahua
Source: custom_components/dahua/client.py:517
Integration: Dahua (documentation, issues)
First occurred: 9:26:42 (1 occurrences)
Last logged: 9:26:42

Could not connect to Dahua device
Traceback (most recent call last):
  File "/config/custom_components/dahua/config_flow.py", line 181, in _test_credentials
    name = await client.get_device_name()
  File "/config/custom_components/dahua/rpc2.py", line 128, in get_device_name
    data = await self.get_config({"name": "General"})
  File "/config/custom_components/dahua/rpc2.py", line 123, in get_config
    response = await self.request(method="configManager.getConfig", params=params)
  File "/config/custom_components/dahua/rpc2.py", line 53, in request
    resp_json = json.loads(await resp.text())
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/dahua/config_flow.py", line 194, in _test_credentials
    data = await client2.get_machine_name()
  File "/config/custom_components/dahua/client.py", line 93, in get_machine_name
    return await self.get(url)
  File "/config/custom_components/dahua/client.py", line 528, in get
    raise exception
  File "/config/custom_components/dahua/client.py", line 517, in get
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url=URL('http://xxx.xxx.x.xx:80/cgi-bin/magicBox.cgi?action=getMachineName')

and this:

Denne feilen stammer fra en tilpasset integrasjon.

Logger: custom_components.dahua
Source: custom_components/dahua/config_flow.py:190
Integration: Dahua (documentation, issues)
First occurred: 9:26:42 (1 occurrences)
Last logged: 9:26:42

Could not connect to Dahua device via the RPC2 API, falling back to cgi

I can get a picture if I use this in config yaml:

camera:
  - platform: ffmpeg
    name: xxxxx
    input: rtsp://admin:xxxxx@xxx.xxx.x.xx:554

**Comment by rroller** [comment]
Sorry for the lack of updates here. Please follow https://github.com/rroller/dahua/issues/6 which will fix the issue for these dome style cameras (I'm not sure when that will get resolved, it's a hard problem... but I'll keep that issue updated with any new information)
