### ISSUE TITLE
Add Amcrest model IP8M-2796E-AI 

### ISSUE THREAD

**Issue by alpauna** [rroller/dahua#346]
This model has a White Light and it is not working with this integration. It does work with video however it is not turning on the "Flood light:. Modifying the script at **line 535 in __init__.py** by adding or self.model.startswith("IP8M")
``` py
# supports_security_light function staring at line 530
def supports_security_light(self) -> bool:
        """
        Returns true if this camera has the red/blue flashing security light feature.  For example, the
        IPC-HDW3849HP-AS-PV does https://dahuawiki.com/Template:NameConvention
        """
        return "-AS-PV" in self.model or self.model == "AD410" or self.model.startswith("IP8M")

```
Added security light and illumination. Also, security light works with this in HA I can turn on and off with events from frigate. So, that is working good for me. I can check that in if that would be helpful. What is your checkin procedure? 

I will keep messing with illumination as it should support 0 - 100 as other cameras do. Currently it is showing as a on / off switch only. This simple modify above at least made it usable with HA so that I can control via Frigate AI. 

Thanks for the awesome integration I have been using for quite some time!

**Comment by coolhand72** [comment]
My IP8M-2779EW-AI no longer works with the integration.  Unsure if this is related, but this a recent issue.  Upgraded to newest firmware V3.000.00AC007.0.R, Build Date: 2023-11-20 has not helped.  The camera is only recognized by the integration as "Generic RTSP by Dahua Firmware: 1.0".  None of the entities work any longer.  Camera is properly logging events and video over the camera's web interface as well as expected in the surveillance software.

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:239
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:11:48 PM (37 occurrences)
Last logged: 11:14:44 PM

[140003611895872] 401, message='Unauthorized', url=URL('http://192.168.50.111:16160/cgi-bin/configManager.cgi?action=setConfig&MotionDetect%5B0%5D.Enable=true&MotionDetect%5B0%5D.DetectVersion=V3.0')
[140002881937600] 401, message='Unauthorized', url=URL('http://192.168.50.111:16160/cgi-bin/configManager.cgi?action=setConfig&Lighting%5B0%5D%5B0%5D.Mode=Manual&Lighting%5B0%5D%5B0%5D.MiddleLight%5B0%5D.Light=39')
[140002881937600] 401, message='Unauthorized', url=URL('http://192.168.50.111:16160/cgi-bin/configManager.cgi?action=setConfig&Lighting%5B0%5D%5B0%5D.Mode=Off&Lighting%5B0%5D%5B0%5D.MiddleLight%5B0%5D.Light=39')
[140002881937600] 401, message='Unauthorized', url=URL('http://192.168.50.111:16160/cgi-bin/configManager.cgi?action=setConfig&MotionDetect%5B0%5D.Enable=true&MotionDetect%5B0%5D.DetectVersion=V3.0')
[140002881937600] 401, message='Unauthorized', url=URL('http://192.168.50.111:16160/cgi-bin/configManager.cgi?action=setConfig&MotionDetect%5B0%5D.Enable=false&MotionDetect%5B0%5D.DetectVersion=V3.0')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/adaptive_lighting/hass_utils.py", line 61, in service_func_proxy
    await existing_service.job.target(call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 905, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 628, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/dahua/light.py", line 92, in async_turn_on
    await self._coordinator.client.async_set_lighting_v1(channel, True, dahua_brightness)
  File "/config/custom_components/dahua/client.py", line 332, in async_set_lighting_v1
    return await self.async_set_lighting_v1_mode(channel, mode, brightness)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dahua/client.py", line 349, in async_set_lighting_v1_mode
    return await self.get(url)
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dahua/client.py", line 792, in get
    raise exception
  File "/config/custom_components/dahua/client.py", line 775, in get
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url=URL('http://192.168.50.111:16160/cgi-bin/configManager.cgi?action=setConfig&Lighting%5B0%5D%5B0%5D.Mode=Manual&Lighting%5B0%5D%5B0%5D.MiddleLight%5B0%5D.Light=39')

**Comment by alpauna** [comment]
Just tested on 0.9.54 the lines have moved to 537 but otherwise it works just the same.

**Comment by zios0007** [comment]
This is in. `IP8M-2796E` is in the security light check:

```python
or m.startswith("IP8M-2796E")
```

so the entity is created without anyone editing `__init__.py`.

@alpauna thank you for retesting it against two versions and reporting the moving line number rather than just saying it still failed. That is what made it straightforward to land.

Worth knowing the wider direction, since this issue is an instance of it: deciding capabilities by matching model strings cannot keep up with OEM rebrands, so it is being replaced by asking the device what it supports (#676). Your camera is covered either way.

@rroller closeable.
