### ISSUE TITLE
Port could not be cast to integer value

### ISSUE THREAD

**Issue by lkoniecki** [rroller/dahua#362]
Parsing the url, if the camera password contains special characters does not work. Looks like the logic of getting the port is wrong. 

Exception in the HA log:

```
2024-06-11 16:25:03.639 ERROR (stream_worker) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 516, in stream_worker
    container = av.open(source, options=pyav_options, timeout=SOURCE_TIMEOUT)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "av/container/core.pyx", line 398, in av.container.core.open
  File "av/container/core.pyx", line 270, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 290, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.ValueError: [Errno 22] Invalid argument: 'rtsp://user:pass@ip:554/cam/realmonitor?channel=3&subtype=0'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/yarl/_url.py", line 191, in __new__
    port = val.port
           ^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'pass'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/homeassistant/homeassistant/components/stream/__init__.py", line 438, in _run_worker
    stream_worker(
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 520, in stream_worker
    f" {redact_credentials(str(source))}"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/stream/__init__.py", line 100, in redact_credentials
    yurl = URL(url)
           ^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yarl/_url.py", line 193, in __new__
    raise ValueError(
ValueError: Invalid URL: port can't be converted to integer
```

See:

```
Port could not be cast to integer value as 'pass'
```

Instead of getting the 554 port, it got password value from the URL.

**Comment by zios0007** [comment]
Fixed in #760, and your error was reproduced exactly.

A password containing `@`, `:` or `/` changes where the URL's authority ends, so the parser reads part of the password as the host or the port:

```
rtsp://admin:p@ss:w/rd#1@10.0.0.5
ValueError: Port could not be cast to integer value as 'w'
```

That is your message, from the same cause.

The main and sub stream URLs had already been fixed by percent-encoding the credentials. The fourth stream is built by a separate branch a few lines below and was missed, and it is reachable: the camera platform creates one stream per index in `range(get_max_streams())`, so any device reporting four streams builds a URL through it. That is why this can look like a problem with one particular stream while the others work.

Both branches encode now, with tests that assert the host survives a punctuated password rather than checking for a particular encoding.

Thank you for diagnosing it as a parsing problem rather than reporting it as "the stream does not work". That is why it was findable.
