### ISSUE TITLE
Error:  Unexpected error fetching dahua data/ Failed to initialize device at 192.168.2.x

### ISSUE THREAD

**Issue by anue87** [rroller/dahua#378]
After upgrade to 0.9.60 i got the following error massages and the my doorbell stoped working.

My system: 
Core: 2024.8.1
Supervisor: 2024.08.0
Operating System: 13.0
Frontend: 20240809.0

Logger: custom_components.dahua
Quelle: helpers/update_coordinator.py:354
Integration: Dahua ([Dokumentation](https://github.com/rroller/dahua), [Probleme](https://github.com/rroller/dahua/issues))
Erstmals aufgetreten: 10:14:00 (4 Vorkommnisse)
Zuletzt protokolliert: 10:15:37

Unexpected error fetching dahua data
Traceback (most recent call last):
  File "/config/custom_components/dahua/client.py", line 758, in get_bytes
    response = await auth.request("GET", self._base + url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dahua/digest.py", line 50, in request
    return await self._handle_401(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/config/custom_components/dahua/digest.py", line 46, in request
    response = await self.session.request(method, url, headers=headers, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 684, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 999, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/dahua/__init__.py", line 225, in _async_update_data
    await self.client.async_get_snapshot(0)
  File "/config/custom_components/dahua/client.py", line 74, in async_get_snapshot
    return await self.get_bytes(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dahua/client.py", line 754, in get_bytes
    async with async_timeout.timeout(TIMEOUT_SECONDS):
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dahua/__init__.py", line 293, in _async_update_data
    raise PlatformNotReady("Dahua device at " + self._address + " isn't fully initialized yet")
homeassistant.exceptions.PlatformNotReady: Dahua device at 192.168.2.110 isn't fully initialized yet

And: 

Logger: custom_components.dahua
Quelle: custom_components/dahua/__init__.py:225
Integration: Dahua ([Dokumentation](https://github.com/rroller/dahua), [Probleme](https://github.com/rroller/dahua/issues))
Erstmals aufgetreten: 10:14:00 (4 Vorkommnisse)
Zuletzt protokolliert: 10:15:37

Failed to initialize device at 192.168.2.110
Traceback (most recent call last):
  File "/config/custom_components/dahua/client.py", line 758, in get_bytes
    response = await auth.request("GET", self._base + url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dahua/digest.py", line 50, in request
    return await self._handle_401(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dahua/digest.py", line 151, in _handle_401
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dahua/digest.py", line 46, in request
    response = await self.session.request(method, url, headers=headers, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 684, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 999, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/dahua/__init__.py", line 225, in _async_update_data
    await self.client.async_get_snapshot(0)
  File "/config/custom_components/dahua/client.py", line 74, in async_get_snapshot
    return await self.get_bytes(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dahua/client.py", line 754, in get_bytes
    async with async_timeout.timeout(TIMEOUT_SECONDS):
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

**Comment by anue87** [comment]
Hi @rroller or somebody else, I would really appreciate your support. I'm unable to fix it, even after a long time of investigation. Thanks in advance."

**Comment by zios0007** [comment]
@anue87 sorry this went unanswered for so long.

A device that initialised before 0.9.60 and not after needs the current error rather than the old one, because failures are now reported specifically. Every failure used to arrive as the same message; a refused password, a timeout, a TLS problem and a device that is reachable but not answering are four different ones now, and that alone usually identifies it.

So the useful first step is a retest on a current version and reading what it says.

Two things that have changed and could be the cause:

- a camera answering with a Basic challenge rather than a Digest one was read as a wrong password (#733)
- a failed setup now gives back its session and its connection pool reference, which it did not before, so a device that comes and goes no longer degrades the instance while it retries

If it still fails, the diagnostics file from the device page, three dots, Download diagnostics, says more than a log excerpt and is redacted.
