### ISSUE TITLE
Failed to sync device state

### ISSUE THREAD

**Issue by mrbarbz** [rroller/dahua#50]
## Configuration

```yaml

Add your logs here.

```

## Describe the bug
After installing the integration I get the following error logs 
I've get 3 different ones which I've labelled them as Log 1, Log 2 and Log 3

Anyone able to help out as to why I'm getting this message. 

Home assistant version :2021.6.3
Dahua integration version : 0.9.1

## Debug log

```text

Add your logs here.

Log 1
This error originated from a custom integration.

Logger: custom_components.dahua
Source: custom_components/dahua/client.py:551
Integration: Dahua (documentation, issues)
First occurred: 7:10:03 AM (96 occurrences)
Last logged: 9:16:14 AM

Failed to sync device state
Traceback (most recent call last):
  File "/config/custom_components/dahua/__init__.py", line 239, in _async_update_data
    results = await asyncio.gather(*coros)
  File "/config/custom_components/dahua/client.py", line 168, in async_common_config
    return await self.get(url)
  File "/config/custom_components/dahua/client.py", line 565, in get
    raise exception
  File "/config/custom_components/dahua/client.py", line 551, in get
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('http://10.0.0.100:80/cgi-bin/configManager.cgi?action=getConfig&name=MotionDetect&action=getConfig&name=Lighting%5B1%5D%5B0%5D')


Log 2 
This error originated from a custom integration.

Logger: custom_components.dahua
Source: custom_components/dahua/__init__.py:210
Integration: Dahua (documentation, issues)
First occurred: 7:10:03 AM (96 occurrences)
Last logged: 9:16:14 AM

Cam does not support profile mode. Will use mode 0

Log 3
Logger: homeassistant.config_entries
Source: config_entries.py:324
First occurred: 7:10:03 AM (2 occurrences)
Last logged: 7:12:45 AM

Config entry 'NVR' for dahua integration not ready yet; Retrying in background
```

**Comment by rroller** [comment]
What model camera do you have?

**Comment by rroller** [comment]
Did you try to use a channel other than "0"?

**Comment by rroller** [comment]
From the logs it looks like it. NVR support is not fully working yet. You can follow along in https://github.com/rroller/dahua/issues/9

**Comment by mrbarbz** [comment]
NVR model - DHI-NVR4208-8P-4Ks2

**Comment by rroller** [comment]
Ah yes, this is the same NVR issue. I'll close this issue in favor of https://github.com/rroller/dahua/issues/9

You can also update to the latest version which might fix your issue. Thanks!
