### ISSUE TITLE
Not loading with DVR because devicetype is empty. 

### ISSUE THREAD

**Issue by voskuh** [rroller/dahua#59]
Thanks for the efforts creating this component. I'm trying to use the component for a DVR (XVR5108C-X). The integration is not loading correctly as shown in the debug logs. 

```
2021-07-21 19:01:02 INFO (MainThread) [custom_components.dahua] Authenticated with the RPC2 API
2021-07-21 19:01:05 WARNING (MainThread) [custom_components.dahua] Failed to sync device state
Traceback (most recent call last):
File "/config/custom_components/dahua/__init__.py", line 197, in _async_update_data
is_doorbell = self.is_doorbell()
File "/config/custom_components/dahua/__init__.py", line 411, in is_doorbell
m = self.model.upper()
AttributeError: 'NoneType' object has no attribute 'upper'
2021-07-21 19:01:05 DEBUG (MainThread) [custom_components.dahua] Finished fetching dahua data in 0.186 seconds

```
The problem is that the output of "/cgi-bin/magicBox.cgi?action=getSystemInfo" doesn't contain a deviceType as stated on line 73 in client.py. 
This is the output. 
```
processor=ST7108
serialNumber=...
updateSerial=XVR5108C-X

```
Maybe it's an idea to retrieve the device type from updateSerial if the output of the Dahua api doesn't contain a deviceType (like you did when the deviceType is IP Camera) or call "/cgi-bin/magicBox.cgi?action=getDeviceType" ?

output of /cgi-bin/magicBox.cgi?action=getDeviceType is 
`type=DH-XVR5108C-X `

Thanks in advance!

**Comment by rroller** [comment]
I've tried to fix this in 0.9.10 https://github.com/rroller/dahua/releases/tag/0.9.10

Can you give that a try? Thanks for the all the detail in the description, helped a lot!

**Comment by voskuh** [comment]
Works great!

**Comment by rroller** [comment]
Thank you!
