### ISSUE TITLE
Following error in my logs

### ISSUE THREAD

**Issue by larsoss** [rroller/dahua#63]
Hello, i have the following error in my logs? What is it? And what can i do about it?
I'm using version 0.9.10 of the Dahua intergration true hacs.
And my version from Home Assistant is  2021.7.4

`Logger: custom_components.dahua
Source: custom_components/dahua/digest.py:46
Integration: Dahua (documentation, issues)
First occurred: 27 juli 2021 23:14:22 (1273 occurrences)
Last logged: 11:57:23

Failed to sync device state
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.114', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/dahua/__init__.py", line 246, in _async_update_data
    results = await asyncio.gather(*coros)
  File "/config/custom_components/dahua/client.py", line 181, in async_common_config
    return await self.get(url)
  File "/config/custom_components/dahua/client.py", line 585, in get
    raise exception
  File "/config/custom_components/dahua/client.py", line 570, in get
    response = await auth.request("GET", url)
  File "/config/custom_components/dahua/digest.py", line 46, in request
    response = await self.session.request(method, url, headers=headers, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.114:80 ssl:default [Connect call failed ('192.168.1.114', 80)]
`

**Comment by rroller** [comment]
> Connect call failed ('192.168.1.114', 80)
> Cannot connect to host 192.168.1.114:80 ssl:default [Connect call failed ('192.168.1.114', 80)]

Are you able to load the following? What's the output you get?

http://192.168.1.114/cgi-bin/magicBox.cgi?action=getSystemInfo

**Comment by rroller** [comment]
Please reopen if you still have the issue
