### ISSUE TITLE
Missing support for IPC-HDBW2431R-ZS-S2

### ISSUE THREAD

**Issue by andilge** [rroller/dahua#77]
I constantly get
-Failed to sync device state
- Could not connect to Dahua device
errors.

HA log says
This error originated from a custom integration.

Logger: custom_components.dahua
Source: custom_components/dahua/client.py:615
Integration: Dahua (documentation, issues)
First occurred: 14:53:57 (13 occurrences)
Last logged: 15:03:33

Failed to sync device state
Could not connect to Dahua device
Traceback (most recent call last):
  File "/config/custom_components/dahua/__init__.py", line 167, in _async_update_data
    responses = await asyncio.gather(
  File "/config/custom_components/dahua/client.py", line 81, in async_get_system_info
    return await self.get(url)
  File "/config/custom_components/dahua/client.py", line 629, in get
    raise exception
  File "/config/custom_components/dahua/client.py", line 615, in get
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://192.168.190.10:443/cgi-bin/magicBox.cgi?action=getSystemInfo')

Do I need to activate the wrapper?

**Comment by rroller** [comment]
Ah very sorry, the integration doesn't yet support this camera :-( 

Please follow this issue https://github.com/rroller/dahua/issues/6 which when completed will work for your cam too. FYI, it's a hard problem :)

**Comment by andilge** [comment]
tnx for getting back so swiftly, looking forward to progresses.
