### ISSUE TITLE
Error service camera snapshot required width and height

### ISSUE THREAD

**Issue by maxoss** [rroller/dahua#86]
## Version of the custom_component
0.9.23

## Describe the bug
When using service camera snapshot I get the an error.

## Debug log

Logger: homeassistant.helpers.script.websocket_api_script
Source: components/camera/__init__.py:751
First occurred: 12:14:15 (1 occurrences)
Last logged: 12:14:15

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: async_camera_image() missing 2 required positional arguments: 'width' and 'height'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 751, in async_handle_snapshot_service
    image = await camera.async_camera_image()
TypeError: async_camera_image() missing 2 required positional arguments: 'width' and 'height'

Logger: homeassistant.components.websocket_api.http.connection
Source: components/camera/__init__.py:751
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:14:15 (1 occurrences)
Last logged: 12:14:15

[547612669888] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 525, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1219, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 751, in async_handle_snapshot_service
    image = await camera.async_camera_image()
TypeError: async_camera_image() missing 2 required positional arguments: 'width' and 'height'

**Comment by pepe59** [comment]
The IPC-A26 does not take a picture. Error in log
```
Logger: homeassistant.components.automation.nova_automatizace_3
Source: components/camera/__init__.py:751
Integration: Automatizace (documentation, issues)
First occurred: 22:35:44 (2 occurrences)
Last logged: 22:35:44

Alarm aktivace/foto kamera: Error executing script. Unexpected error for call_service at pos 1: async_camera_image() missing 2 required positional arguments: 'width' and 'height'
While executing automation automation.nova_automatizace_3
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 751, in async_handle_snapshot_service
    image = await camera.async_camera_image()
TypeError: async_camera_image() missing 2 required positional arguments: 'width' and 'height'
```

**Comment by JustinScott** [comment]
A workaround for this error is to create a separate camera like this.
 
- platform: generic
  name: CAMERA
  still_image_url: http://192.168.X.X/cgi-bin/snapshot.cgi
  stream_source: rtsp://XXX:XXX@192.168.X.X:554/cam/realmonitor?channel=1&subtype=0
  verify_ssl: false
  username: XXX
  password: XXX
  authentication: digest

**Comment by zuohaot** [comment]
Same problem found after the latest update. It was working well in the previous release

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/camera/__init__.py:751
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:38:02 PM (3 occurrences)
Last logged: 9:40:48 PM

[140174619042864] async_camera_image() missing 2 required positional arguments: 'width' and 'height'
[140174501011856] async_camera_image() missing 2 required positional arguments: 'width' and 'height'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 751, in async_handle_snapshot_service
    image = await camera.async_camera_image()
TypeError: async_camera_image() missing 2 required positional arguments: 'width' and 'height'
`

**Comment by TheBisk** [comment]
Same error here, started from HA version 2021.9.7.

TypeError: async_camera_image() missing 2 required positional arguments: 'width' and 'height'

**Comment by rroller** [comment]
Sorry for the issues. How are you reproducing this? I'm having trouble trying to repo. Once I have a repo I can fix it rather easy.

**Comment by jgverweij** [comment]
> Sorry for the issues. How are you reproducing this? I'm having trouble trying to repo. Once I have a repo I can fix it rather easy.

Call service in action of automation:
`service: camera.snapshot
target:
  entity_id: camera.dahua_sub
data:
  filename: /media/camera_snapshots/dahua.jpg
`

**Comment by Hrupek** [comment]
same error for me new set up

**Comment by GeitjeG** [comment]
Check out here under breaking changes -> scroll down to -> custom integration: camera's
https://www.home-assistant.io/blog/2021/09/01/release-20219/#breaking-changes

I think this should be changed and it's working again?

**Comment by fokcuk** [comment]
detailed here:
[https://github.com/home-assistant/core/pull/53835]

**Comment by theetron** [comment]
Would be nice if this can be fixed soon.

**Comment by rroller** [comment]
My plan is to work on this over the weekend

**Comment by rroller** [comment]
@GeitjeG Thanks for that. Now I can reproduce this. Digging deeper now for a fix.

**Comment by rroller** [comment]
This should do it - https://github.com/rroller/dahua/commit/83c09300098b6e446d218a60280a7d5babfd2c6f

Try 0.9.24

https://github.com/rroller/dahua/releases/tag/0.9.24

**Comment by theetron** [comment]
I can confirm the snapshot is working again with 0.9.24. Thanks!

**Comment by pansinmanteca** [comment]
it's working again. Thanks!

**Comment by GeitjeG** [comment]
Great, it's working again! Thanks for your efforts.
