### ISSUE TITLE
Restart HA will random cause one camera fail to establish

### ISSUE THREAD

**Issue by sasukebinbin** [rroller/dahua#98]
Logger: custom_components.dahua
Source: custom_components/dahua/client.py:612
Integration: Dahua (documentation, issues)
First occurred: 24:34:36 (11 occurrences)
Last logged: 24:46:16

Failed to sync device state
Traceback (most recent call last):
  File "/config/custom_components/dahua/client.py", line 606, in get_bytes
    response = await auth.request("GET", self._base + url)
  File "/config/custom_components/dahua/digest.py", line 50, in request
    return await self._handle_401(response)
  File "/config/custom_components/dahua/digest.py", line 151, in _handle_401
    return await self.request(
  File "/config/custom_components/dahua/digest.py", line 46, in request
    response = await self.session.request(method, url, headers=headers, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/dahua/__init__.py", line 171, in _async_update_data
    await self.client.async_get_snapshot(0)
  File "/config/custom_components/dahua/client.py", line 67, in async_get_snapshot
    return await self.get_bytes(url)
  File "/config/custom_components/dahua/client.py", line 612, in get_bytes
    response.close()
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

**Comment by rroller** [comment]
Unlikely this is anything to do with the integration but something one off with your setup or camera. Not a lot I can do here.
